### ISSUE TITLE
Questions about the HMBA_Human_BG_annotation

### ISSUE THREAD

**Issue by DingWB** [AllenInstitute/scrattch.taxonomy#29]
Hi @UCDNJJ ,

Regarding the cell type annotation table, I have two questions:
(1). In table "HMBA_Human_BG_annotation", you only provided marker genes for the level 4 cluster (Group). The marker genes for levels 1-3 are also needed to perform iterative clustering. Do you have the marker genes for levels 1-3 (Neighborhood, class and subclass)?

(2). Could you please explain the difference between "NSForest_markers" and "binary_genes"?

**Comment by UCDNJJ** [comment]
Hi @DingWB 

We've computed marker genes using NSForest which is at the cluster level not Group actually. I don't exactly follow what you mean by: "The marker genes for levels 1-3 are also needed to perform iterative clustering." Can you clarify?

To cluster we used: https://github.com/AllenInstitute/transcriptomic_clustering that doesn't compute marker genes at higher level annotations like Group, etc.

NSForest_markers: Combination of genes that are needed to accurately identify a cluster
Binary_genes: Single genes that individually mark a cluster.

**Comment by DingWB** [comment]
Hi @UCDNJJ ,

For iterative clustering, we will first cluster cells into 3 superclasses (for example Excitatory neurons, inhibitory neurons, and non-neurons) based on the collected marker genes, this is level 1. Then perform level 2 clustering to get subtypes for each superclass, for example, non-neurons can be further clustered into ASC, ODC, PC, etc. al.

I was wondering whether you have the list of marker genes for levels 1-3, such as marker genes for each neighborhood, class and subclass.

**Comment by UCDNJJ** [comment]
Hi @DingWB 

The process you described sounds exactly like hierarchical cell type mapping which we've provided access to via the AIT .h5ad files either through scrattch.mapping (R) or cell_type_mapper (python) both of which are linked to here: https://docs.google.com/document/d/1aP3yfpGT4rtI01lZ6-TB4wpPQU4U9sIlTQJVQa9DARA/edit#heading=h.o50obbrfixzs 

If you need marker genes for each level of the hierarchy to do this process manually you can pull those from the files computed by cell_type_mapper which are embedded in the AIT .h5ad objects at AIT_anndata.uns.hierarchical["standard"]. We could write a helper function to pull the marker genes out of each node in the hierarchy if you need, please let us know.

**Comment by DingWB** [comment]
Thank you @UCDNJJ .

I found those markers in `adata.uns.hierarchical["standard"]`, I will extract those markers myself.
Thanks for your help.

**Comment by DingWB** [comment]
Hi @UCDNJJ ,

I checked adata.uns.hierarchical["standard"] and found that the marker genes for neighborhood and some of class are empty. Could you please provide the marker genes for these levels?

**Comment by UCDNJJ** [comment]
@danielsf, @inkarkapen Can you clarify on missing marker genes for certain levels in the precomputed stats files for cell_type_mapper? 

In general @DingWB, we rely on mapping tools to assign these labels across datasets and thus have not explicitly defined marker gene panels for all levels of the taxonomy. We will do this eventually but for now we don't have markers to provide. We envision BICAN groups mapping their data into our references using tools like `cell_type_mapper` and `scrattch.mapping`.

Can you comment on why cell type mapping tools do not suite your needs? I know you are interested in ?manual? iterative clustering but I don't quite see the difference in what you are doing as compared to hierarchical mapping in `cell_type_mapper`.

**Comment by DingWB** [comment]
Hi @UCDNJJ ,

I am not sure whether `cell_type_mapper` works on our methylation data. I will explore this package and let you know the result.

**Comment by danielsf** [comment]
Regarding the missing markers:

All of the neighborhoods and classes that have 0 markers associated with them have exactly one child in the taxonomy tree (for instance, the class 'CN CGE GABA' descends directly to the subclass 'CN CGE VIP GABA' and no other subclasses). Since, according to the cell_type_mapper's hierarchical mapping, this is an uninteresting case (once you "know" your cell belongs to CN CGE GABA, you must, according to the taxonomy tree, "know" that your cell belongs to CN CGE VIP GABA), it does not bother to find marker genes for CN CGE GABA.

At this point, it is probably worth pointing out that when the cell_type_mapper talks about "markers for the class Astro-Epen", it means "markers that are good at discriminating between the children of Astro-Epen". This is documented [on this page](https://github.com/AllenInstitute/cell_type_mapper/blob/main/docs/input_data_files/marker_gene_lookup.md).

The broader hierarchical mapping algorithm used by the cell_tyep_mapper is discussed [on this page](https://github.com/AllenInstitute/cell_type_mapper/blob/main/docs/algorithms/hierarchical_mapping.md) and [in this video](https://youtu.be/JjzRMF3lyK0?t=1589).

Let me know if you have any other questions I can answer.

**Comment by UCDNJJ** [comment]
Thanks for the clarification Scott. 

Following up on: "cell_type_mapper talks about "markers for the class Astro-Epen", it means "markers that are good at discriminating between the children of Astro-Epen". To me this means that it wouldn't be appropriate for folks to try and pull marker gene sets to discriminate individual nodes in the hierarchy from the cell_type_mapper. Is that correct?

**Comment by UCDNJJ** [comment]
@DingWB 

Here's potentially some helpful notes that Hanqing Liu shared with me awhile ago for a similiar problem on mapping RNA-seq labels onto methylation data:

``` 
    # You can use the cell-by-gene table for integrating and mapping mC data with RNA data. Here is an example:
    # https://lhqing.github.io/ALLCools/cell_level/integration/multi_modalities/Neurons/04-integration.html
    # Some main steps:
    # 1. Select highly variable genes as you would normally do for other integrations, usually I select HVGs from RNA data, and directly use these genes on integration. But you can also try to select HVGs from mC data and intersect the two HVG list.
    # 2. mC data MUST be reversed (max(X) - X or X*-1 if scaled), because the mC fraction values are negatively correlated to RNA in general
    # 3. Use what ever integration methods you like (Seurat, Harmony, LIGER, Scanorama) to perform integration and label transfer if you are using Seurat.
    # Besides, separate neurons and non-neurons might be better, and neurons has very diverse mCH fractions in their gene bodies, while non-neurons have much less diversity in mCH and we usually use mCG fraction.
```
You can essentially replace Seurat with cell_type_mapper or scrattch.mapping. Hope this helps.

**Comment by danielsf** [comment]
> Thanks for the clarification Scott.
> 
> Following up on: "cell_type_mapper talks about "markers for the class Astro-Epen", it means "markers that are good at discriminating between the children of Astro-Epen". To me this means that it wouldn't be appropriate for folks to try and pull marker gene sets to discriminate individual nodes in the hierarchy from the cell_type_mapper. Is that correct?

@UCDNJJ that is correct. By the time they get to the marker gene lookup table that the cell_type_mapper consumes, the marker genes have been combinatorially processed to select the minimal set of markers that is effective* at discriminating between the children of a given parent node under the assumption that the cell is definitely a member of the parent node. This is a different thing than "marker genes I can look for to identify a specific node without any other prior knowledge."

*reasonable people can disagree on the definition of "minimal" and "effective", which is why the actual mapping step of the cell_type_mapper lets you pass in your own bespoke marker lookup table should you so choose.
